### PR TITLE
fix: some minor Typos

### PR DESCRIPTION
**Pull request by kode15333**
## Details
Found some typos(min -> max)

### CODE REVIEW

**Comment by WoodNeck** [comment]
Thanks for the PR 🤗
But as our documentations are all auto-generated, you should fix the jsdoc in the src files instead of actual docs.

**Comment by kode15333** [comment]
Thank you 
i fixed the jsdoc

**Review by daybrush — APPROVED** [review]
Thank you for PR :) Good.

**Review by WoodNeck — APPROVED** [review]
Great :)

**Comment by WoodNeck** [comment]
@kode15333 Can you rebase it to the current master branch?
We've removed the older trivial versions in the docs folder, so it's conflicting now.

**Comment by kode15333** [comment]
I think something is wrong...
Sorry

**Comment by WoodNeck** [comment]
@kode15333
Try this:
```bash
git remote add upstream git@github.com:naver/egjs-flicking.git
git fetch upstream
git checkout master
git reset --hard upstream/master
git cherry-pick f6d521b
git cherry-pick 09903c2
git push origin master -f
```

It resets your branch to the current master branch and adds your commits on top of them.
Your commits might conflict with the current master branch, so it can require some additional modifications.

Well, I can do this for you instead if you're not willing to. PRs are always welcome though :)

**Comment by kode15333** [comment]
thanks a lot

**Comment by WoodNeck** [comment]
Commits are still mixed I see?
The final form should include only the commits of your own.

**Comment by kode15333** [comment]
This time, I'll close this PR.

**Pull request closed without merging**
