### PR TITLE
fix: vue-flicking panels are targeting old element

### LINKED ISSUE #617: Cannot manipulate DOM when `renderOnlyVisible` is enabled (vue2)
## Description

I tried to directly manipulate the DOM by doing: `panel.element.classList.add('something')`, but it didn't work. After that I tried to remove `renderOnlyVisible` to see if it works without that property. I don't know why/how but it worked as expected!

BTW I noticed this #585 . I think it's related to my issue.

Version: `4.5.1`

### PR DESCRIPTION
**Pull request by WoodNeck**
## Issue
#609, #617

## Details
This fixes #617

### CODE REVIEW

**Review by malangfox — APPROVED** [review]
LGTM

**Comment by cc00010** [comment]
@daybrush ping?

**Review by daybrush — APPROVED** [review]
LGTM

**Comment by cc00010** [comment]
thanks!

**Pull request merged**
