### PR TITLE
style(utils): Remove outdated .isHWAccelerable()

### PR DESCRIPTION
**Pull request by netil**
## Issue

#66

## Details

Remove unused & outdated code

### CODE REVIEW

**Comment by sculove** [comment]
@netil the default value of hwAccelerable is true.
How about changing default value of hwAccelerable option?
eg.Flicking should support android 2.3+
so, How about changing default value of hwAccelerable option from 'true' to the result value of the isHWAccelerable function?

**Comment by netil** [comment]
@sculove I don't think so.
The usage environment was upgraded comparing years ago. I know that there're still low efficiency devices out there, but we need to cut the support in certain time.

**Comment by sculove** [comment]
@netil ok. you'd better correct browser coverages

**Comment by sculove** [comment]
LGTM

**Comment by netil** [comment]
@sculove I think it's good to have some discussion about it.

**Comment by netil** [comment]
Adding code snippet url for the removed code will be enough

**Comment by netil** [comment]
To check the support of CSS transform and HW acceleration, check out the below snippet
- https://gist.github.com/netil/c1d1b67e1c1926364c0709f110a09b44

**Pull request merged**
