### PR TITLE
feat(ngx-flicking): upgrade to Angular 15 and enable partial compilation

### PR DESCRIPTION
**Pull request by arturovt**

### CODE REVIEW

**Review by WoodNeck — APPROVED** [review]
LGTM, thanks for the hard work!

**Comment by arturovt** [comment]
Put on the hold for now since need to make unit tests running in `cfc/.../angular`.

**Review by malangfox — APPROVED** [review]
LGTM 👍 
If you encounter any issues with the unit test update, we'd love to know more about it.

**Comment by malangfox** [comment]
@arturovt 

We appreciate the changes you've made and want to apply them to our main branch.
If it's difficult to complete the cfc test shortly, we'd like to complete your work. 
If there is no comment within 5 days, we will continue this work ourselves.

**Comment by arturovt** [comment]
I'll have a look on weekends, I'll ping you if I ain't able to resolve test issues.

**Comment by arturovt** [comment]
@malangfox I was able to fix cfc tests, at least locally :joy: (hope CI is gonna be green too)

Screenshot from 2023-04-18 00-13-55

**Review by daybrush — APPROVED** [review]
LGTM

**Pull request merged**
