### PR TITLE
fix: change startsWith method

### PR DESCRIPTION
**Pull request by daybrush**
## Issue

#644

### CODE REVIEW

**Review by WoodNeck — APPROVED** [review]
LGTM, but please use more readable code like `name.indexOf("_") !== 0`

**Review by qpitlove — APPROVED** [review]

**Review by malangfox — APPROVED** [review]
LGTM

**Comment by qpitlove** [comment]
plz fix failed test.

**Comment by WoodNeck** [comment]
@qpitlove They're fixed in #646

**Pull request merged**
