### PR TITLE
fix: fix component dependency for frameworks

### PR DESCRIPTION
**Pull request by daybrush**
## Issue

#740

### CODE REVIEW

**Review by WoodNeck — CHANGES_REQUESTED** [review]
I think `ngx-flicking` and `vue-flicking` should be excluded from this PR, as they don't directly import `@egjs/component` in their code.
`ngx-flicking` actually imports `ComponentEvent`, but as it's just importing type from the component, I hope that's okay.
Or, we can  try changing it explicitly like this:
```ts
import type { ComponentEvent } from "@egjs/component";
```

Anyway, I wonder in which env the issue occurs.
As `@egjs/component` is resolved correctly in the same `node_moudles` directory in most cases.

**Comment by daybrush** [comment]
In most cases there is no problem.

There was a report from yarn berry that it was installed as follows.
@egjs/react-flicking
@egjs/flicking
@egjs/flicking/node_modules/@egjs/component


There may be no problems here, but phantom dependencies may have version issues.

**Review by WoodNeck — APPROVED** [review]
LGTM

I think we may have to update the minor version of the framework packages next time, when we upgrade the `@egjs/component` to v4.

**Review by malangfox — APPROVED** [review]
LGTM

**Pull request merged**
